(function() {var implementors = {};
implementors["openvr"] = ["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"openvr/system/struct.HiddenAreaMesh.html\" title=\"struct openvr::system::HiddenAreaMesh\">HiddenAreaMesh</a>&lt;'a&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"openvr/render_models/component/controller/struct.GDC2015.html\" title=\"struct openvr::render_models::component::controller::GDC2015\">GDC2015</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"openvr/render_models/component/controller/struct.BASE.html\" title=\"struct openvr::render_models::component::controller::BASE\">BASE</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"openvr/render_models/component/controller/struct.TIP.html\" title=\"struct openvr::render_models::component::controller::TIP\">TIP</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"openvr/render_models/component/controller/struct.HAND_GRIP.html\" title=\"struct openvr::render_models::component::controller::HAND_GRIP\">HAND_GRIP</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"openvr/render_models/component/controller/struct.STATUS.html\" title=\"struct openvr::render_models::component::controller::STATUS\">STATUS</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
